#!/bin/bash
# run v1.1

if [[ "$@" == "" ]]; then
    docker run -it --rm --name rust -v .:/code -w /code rust:1.91.1-trixie cargo run
else
    echo "command: $@"
    docker run -it --rm --name rust -v .:/code -w /code rust:1.91.1-trixie "$@"
fi

docker run -it --rm --name rust -v .:/code -w /code rust:1.91.1-trixie chown -R $(id -u):$(id -g) .
